using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Mouse.NET.Data;

#nullable disable

namespace Mouse.NET.Migrations;

[DbContext(typeof(MouseDbContext))]
[Migration("20260315195000_RolePolicyBindingsDropPermissions")]
public partial class RolePolicyBindingsDropPermissions : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql(@"
            CREATE TABLE IF NOT EXISTS role_policy_bindings (
                role_id integer NOT NULL,
                policy_type integer NOT NULL,
                policy_key text NOT NULL,
                CONSTRAINT PK_role_policy_bindings PRIMARY KEY (role_id, policy_type, policy_key),
                CONSTRAINT FK_role_policy_bindings_roles_role_id FOREIGN KEY (role_id) REFERENCES roles (""Id"") ON DELETE CASCADE
            );
        ");

        migrationBuilder.Sql(@"DROP TABLE IF EXISTS role_permissions;");
        migrationBuilder.Sql(@"DROP TABLE IF EXISTS permissions;");
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql(@"DROP TABLE IF EXISTS role_policy_bindings;");

        migrationBuilder.Sql(@"
            CREATE TABLE IF NOT EXISTS permissions (
                ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                key text NOT NULL,
                description text NULL,
                CONSTRAINT PK_permissions PRIMARY KEY (""Id"")
            );
        ");

        migrationBuilder.Sql(@"
            CREATE TABLE IF NOT EXISTS role_permissions (
                role_id integer NOT NULL,
                permission_id integer NOT NULL,
                CONSTRAINT PK_role_permissions PRIMARY KEY (role_id, permission_id),
                CONSTRAINT FK_role_permissions_roles_role_id FOREIGN KEY (role_id) REFERENCES roles (""Id"") ON DELETE CASCADE,
                CONSTRAINT FK_role_permissions_permissions_permission_id FOREIGN KEY (permission_id) REFERENCES permissions (""Id"") ON DELETE CASCADE
            );
        ");

        migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS IX_role_permissions_permission_id ON role_permissions (permission_id);");
    }
}
